LightJason - REST: org.lightjason.rest.provider.CAgentGeneratorWrapper Class Reference
org.lightjason.rest.provider.CAgentGeneratorWrapper Class Reference
generator wrapper
Inherits IGeneratorWrapper< IAgentGenerator<?> >.
Public Member Functions
final boolean equals (final Object p_object)
void generate ()
final void generate (final int p_number)
final IAgentGenerator<?> generator ()
final int hashCode ()
Static Public Member Functions
static IGeneratorWrapper
< IAgentGenerator<?> > from (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consume)
factory
static IGeneratorWrapper
< IAgentGenerator<?> > from (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consumer, final Supplier< Object[]> p_supplier)
factory
Private Member Functions
CAgentGeneratorWrapper (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consumer)
ctor
CAgentGeneratorWrapper (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consumer, final Supplier< Object[]> p_supplier)
ctor
Private Attributes
final Consumer< IAgent<?> > m_consumer
consumer of the agents
final IAgentGenerator<?> m_generator
agent generator
final Supplier< Object[]> m_supplier
optional supplier of the generator data
Detailed Description
Definition at line 37 of file CAgentGeneratorWrapper.java.
Constructor & Destructor Documentation
org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consumer) private
Parameters
p_consumer consumer for agents
Template Parameters
T agent type
Definition at line 58 of file CAgentGeneratorWrapper.java.
Referenced by org.lightjason.rest.provider.CAgentGeneratorWrapper.from().
org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consumer, final Supplier< Object[]> p_supplier) private
Parameters
p_consumer consumer for agents
p_supplier supplier for agent generating call
Template Parameters
T agent type
Definition at line 70 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.m_consumer, org.lightjason.rest.provider.CAgentGeneratorWrapper.m_generator, and org.lightjason.rest.provider.CAgentGeneratorWrapper.m_supplier.
Member Function Documentation
final boolean org.lightjason.rest.provider.CAgentGeneratorWrapper.equals (final Object p_object)
Definition at line 103 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.hashCode().
static IGeneratorWrapper<IAgentGenerator<?> > org.lightjason.rest.provider.CAgentGeneratorWrapper.from (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consume) static
Parameters
p_generator agent generator
p_consume consumer
Returns
wrapper instance
Definition at line 115 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper().
static IGeneratorWrapper<IAgentGenerator<?> > org.lightjason.rest.provider.CAgentGeneratorWrapper.from (final IAgentGenerator<?> p_generator, final Consumer< IAgent<?>> p_consumer, final Supplier< Object[]> p_supplier) static
Parameters
p_generator agent generator
p_consumer consumer
p_supplier supplier for genertor parameter
Returns
wrapper instance
Definition at line 128 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper().
void org.lightjason.rest.provider.CAgentGeneratorWrapper.generate ()
Definition at line 79 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.m_supplier.
final void org.lightjason.rest.provider.CAgentGeneratorWrapper.generate (final int p_number)
Definition at line 85 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.m_consumer, and org.lightjason.rest.provider.CAgentGeneratorWrapper.m_supplier.
final IAgentGenerator<?> org.lightjason.rest.provider.CAgentGeneratorWrapper.generator ()
Definition at line 91 of file CAgentGeneratorWrapper.java.
References org.lightjason.rest.provider.CAgentGeneratorWrapper.m_generator.
final int org.lightjason.rest.provider.CAgentGeneratorWrapper.hashCode ()
Definition at line 97 of file CAgentGeneratorWrapper.java.
Referenced by org.lightjason.rest.provider.CAgentGeneratorWrapper.equals().
Member Data Documentation
final Consumer<IAgent<?> > org.lightjason.rest.provider.CAgentGeneratorWrapper.m_consumer private
Definition at line 46 of file CAgentGeneratorWrapper.java.
Referenced by org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper(), and org.lightjason.rest.provider.CAgentGeneratorWrapper.generate().
final IAgentGenerator<?> org.lightjason.rest.provider.CAgentGeneratorWrapper.m_generator private
Definition at line 50 of file CAgentGeneratorWrapper.java.
Referenced by org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper(), and org.lightjason.rest.provider.CAgentGeneratorWrapper.generator().
final Supplier<Object[]> org.lightjason.rest.provider.CAgentGeneratorWrapper.m_supplier private
Definition at line 42 of file CAgentGeneratorWrapper.java.
Referenced by org.lightjason.rest.provider.CAgentGeneratorWrapper.CAgentGeneratorWrapper(), and org.lightjason.rest.provider.CAgentGeneratorWrapper.generate().