LightJason - REST: org.lightjason.rest.provider.CAgentProvider Class Reference
org.lightjason.rest.provider.CAgentProvider Class Reference
agent provider
Inherits IProvider< IAgent<?> >.
Public Member Functions
final Response belief (@PathParam("id") final String p_id,@PathParam("action") final String p_action, final String p_literal)
rest-api call to add a new belief
final Response cycle ()
executes the cycle for all agents
final Response cycle (@PathParam("id") final String p_id)
rest-api call to run a cycle
final Stream< IProvider
< IAgent<?> > > dependprovider ()
final Response goal (@PathParam("id") final String p_id,@PathParam("action") final String p_action,@PathParam("trigger") final String p_trigger, final String p_literal)
rest-api call to trigger a plan
final Response goalimmediately (@PathParam("id") final String p_id,@PathParam("action") final String p_action,@PathParam("trigger") final String p_trigger, final String p_literal)
rest-api call to trigger a plan immediately
final IProvider< IAgent<?> > register (final String p_id, final IAgent<?> p_agent)
final Response sleep (@PathParam("id") final String p_id,@QueryParam("time") final long p_time)
api call to set sleeping state (http get)
final Response sleep (@PathParam("id") final String p_id,@QueryParam("time") final long p_time, final String p_data)
rest-api call to set sleeping state (http post)
final Stream<?extends IAgent<?> > unregister (final String p_id)
final Stream<?extends IAgent<?> > unregister (final IAgent<?>...p_agent)
final Stream<?extends IAgent<?> > unregister (final Stream<?extends IAgent<?>> p_agent)
final Object view ()
returns a list of all registered agent names
final Object view (@PathParam("id") final String p_id)
rest-api call to get current state of the agent
final Response wakeup (@PathParam("id") final String p_id)
rest-api call to run wake-up (http get)
final Response wakeup (@PathParam("id") final String p_id, final String p_data)
rest-api call to run wake-up (http post)
Private Attributes
final BiMap< String, IAgent<?> > m_agents = Maps.synchronizedBiMap(HashBiMap.create())
map with agents
Detailed Description
Definition at line 54 of file CAgentProvider.java.
Member Function Documentation
final Response org.lightjason.rest.provider.CAgentProvider.belief (@PathParam("id") final String p_id, @PathParam("action") final String p_action, final String p_literal)
Parameters
p_id agent identifier
p_action action
p_literal literal
Returns
http response
Definition at line 246 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
final Response org.lightjason.rest.provider.CAgentProvider.cycle ()
Returns
response
Definition at line 138 of file CAgentProvider.java.
final Response org.lightjason.rest.provider.CAgentProvider.cycle (@PathParam("id") final String p_id)
Returns
response
Definition at line 154 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
final Stream<IProvider<IAgent<?> > > org.lightjason.rest.provider.CAgentProvider.dependprovider ()
Definition at line 94 of file CAgentProvider.java.
final Response org.lightjason.rest.provider.CAgentProvider.goal (@PathParam("id") final String p_id, @PathParam("action") final String p_action, @PathParam("trigger") final String p_trigger, final String p_literal)
Parameters
p_id agent identifier
p_trigger trigger type
p_literal literal data
Returns
http response
Definition at line 301 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
final Response org.lightjason.rest.provider.CAgentProvider.goalimmediately (@PathParam("id") final String p_id, @PathParam("action") final String p_action, @PathParam("trigger") final String p_trigger, final String p_literal)
Parameters
p_id agent identifier
p_trigger trigger type
p_literal literal data
Returns
http response
Definition at line 270 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
final IProvider<IAgent<?> > org.lightjason.rest.provider.CAgentProvider.register (final String p_id, final IAgent<?> p_agent)
Definition at line 65 of file CAgentProvider.java.
final Response org.lightjason.rest.provider.CAgentProvider.sleep (@PathParam("id") final String p_id, @QueryParam("time") final long p_time)
Parameters
p_id agent identifier
p_time sleeping time
Returns
http response
Definition at line 176 of file CAgentProvider.java.
final Response org.lightjason.rest.provider.CAgentProvider.sleep (@PathParam("id") final String p_id, @QueryParam("time") final long p_time, final String p_data)
Parameters
p_id agent identifier
p_time sleeping time
p_data wake-up data
Returns
http response
Definition at line 192 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
final Stream<? extends IAgent<?> > org.lightjason.rest.provider.CAgentProvider.unregister (final String p_id)
Definition at line 72 of file CAgentProvider.java.
final Stream<? extends IAgent<?> > org.lightjason.rest.provider.CAgentProvider.unregister (final IAgent<?>... p_agent)
Definition at line 78 of file CAgentProvider.java.
final Stream<? extends IAgent<?> > org.lightjason.rest.provider.CAgentProvider.unregister (final Stream<?extends IAgent<?>> p_agent)
Definition at line 84 of file CAgentProvider.java.
final Object org.lightjason.rest.provider.CAgentProvider.view ()
Returns
agent name list
Definition at line 110 of file CAgentProvider.java.
final Object org.lightjason.rest.provider.CAgentProvider.view (@PathParam("id") final String p_id)
Parameters
p_id agent identifier
Returns
agent object or http error
Definition at line 124 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
final Response org.lightjason.rest.provider.CAgentProvider.wakeup (@PathParam("id") final String p_id)
Parameters
p_id agent identifier
Returns
http response
Definition at line 210 of file CAgentProvider.java.
final Response org.lightjason.rest.provider.CAgentProvider.wakeup (@PathParam("id") final String p_id, final String p_data)
Parameters
p_id agent identifier
p_data data
Returns
http response
Definition at line 225 of file CAgentProvider.java.
References org.lightjason.rest.CCommon.languagestring().
Member Data Documentation
final BiMap<String, IAgent<?> > org.lightjason.rest.provider.CAgentProvider.m_agents = Maps.synchronizedBiMap(HashBiMap.create()) private
Definition at line 59 of file CAgentProvider.java.