LightJason - REST: org.lightjason.rest.provider.CExecution Class Reference
org.lightjason.rest.provider.CExecution Class Reference
execution class of api calls
Static Public Member Functions
static Stream< RuntimeException > belief (final Stream< IAgent<?>> p_agents, final String p_action, final String p_data)
add / deletes an belief
static Stream< Exception > cycle (final Stream< IAgent<?>> p_agents)
runs on an agent stream the cycle
static Stream< RuntimeException > goaltrigger (final Stream< IAgent<?>> p_agents, final String p_action, final String p_trigger, final String p_data, final boolean p_immediately)
trigger a goal
static void sleep (final Stream< IAgent<?>> p_agents, final long p_time, final String p_data)
runs sleeping call
static void wakeup (final Stream< IAgent<?>> p_agents, final String p_data)
runs wake-up calls
Private Member Functions
CExecution ()
ctor
Static Private Member Functions
static< T > boolean actionconsumer (final String p_action, final Stream< T > p_values, final Stream< String > p_possibility, final Stream< Consumer< Stream< T >>> p_executer)
static< R, T > Stream< R > actionfunction (final String p_action, final Stream< T > p_values, final Stream< String > p_possibility, final Stream< Function< T, R >> p_executer)
static Stream< ITerm > parsestringterm (final String p_data)
parses a string to a term set
static ITerm parseterm (final String p_data, final Function< String, ITerm > p_return, final IFunction< String, ITerm >...p_parse)
parse any string data into a term
Detailed Description
Definition at line 50 of file CExecution.java.
Constructor & Destructor Documentation
org.lightjason.rest.provider.CExecution.CExecution () private
Definition at line 55 of file CExecution.java.
Member Function Documentation
static <T> boolean org.lightjason.rest.provider.CExecution.actionconsumer (final String p_action, final Stream< T > p_values, final Stream< String > p_possibility, final Stream< Consumer< Stream< T >>> p_executer) static private
Parameters
p_action action name
p_values value stream
p_possibility stream with possibility of the action
p_executer function for calling on possibility match
Returns
stream with function results
Definition at line 220 of file CExecution.java.
Referenced by org.lightjason.rest.provider.CExecution.belief().
static <R,T> Stream<R> org.lightjason.rest.provider.CExecution.actionfunction (final String p_action, final Stream< T > p_values, final Stream< String > p_possibility, final Stream< Function< T, R >> p_executer) static private
Parameters
p_action action name
p_values value stream
p_possibility stream with possibility of the action
p_executer function for calling on possibility match
Returns
stream with function results
Definition at line 200 of file CExecution.java.
Referenced by org.lightjason.rest.provider.CExecution.goaltrigger().
static Stream<RuntimeException> org.lightjason.rest.provider.CExecution.belief (final Stream< IAgent<?>> p_agents, final String p_action, final String p_data) static
Parameters
p_agents agent stream
p_action action
p_data belief data
Returns
exception stream
Definition at line 118 of file CExecution.java.
References org.lightjason.rest.provider.CExecution.actionconsumer(), org.lightjason.rest.CCommon.languagestring(), and org.lightjason.rest.provider.CExecution.parsestringterm().
static Stream<Exception> org.lightjason.rest.provider.CExecution.cycle (final Stream< IAgent<?>> p_agents) static
Parameters
p_agents agent stream
Returns
stream with execption objects
Definition at line 66 of file CExecution.java.
static Stream<RuntimeException> org.lightjason.rest.provider.CExecution.goaltrigger (final Stream< IAgent<?>> p_agents, final String p_action, final String p_trigger, final String p_data, final boolean p_immediately) static
Parameters
p_agents agent stream
p_action action
p_trigger trigger type
p_data trigger data
p_immediately immediately execution
Returns
error stream
Definition at line 153 of file CExecution.java.
References org.lightjason.rest.provider.CExecution.actionfunction(), org.lightjason.rest.CCommon.languagestring(), and org.lightjason.rest.provider.CExecution.parsestringterm().
static Stream<ITerm> org.lightjason.rest.provider.CExecution.parsestringterm (final String p_data) static private
Parameters
p_data string
Returns
term stream
Definition at line 243 of file CExecution.java.
References org.lightjason.rest.provider.CExecution.parseterm().
Referenced by org.lightjason.rest.provider.CExecution.belief(), org.lightjason.rest.provider.CExecution.goaltrigger(), org.lightjason.rest.provider.CExecution.sleep(), and org.lightjason.rest.provider.CExecution.wakeup().
static ITerm org.lightjason.rest.provider.CExecution.parseterm (final String p_data, final Function< String, ITerm > p_return, final IFunction< String, ITerm >... p_parse) static private
Parameters
p_data string data
p_return return argument if all parsing functions are failing
p_parse parsing function
Returns
term
Definition at line 268 of file CExecution.java.
Referenced by org.lightjason.rest.provider.CExecution.parsestringterm().
static void org.lightjason.rest.provider.CExecution.sleep (final Stream< IAgent<?>> p_agents, final long p_time, final String p_data) static
Parameters
p_agents agent stream
p_time sleeping time
p_data any optional data
Definition at line 91 of file CExecution.java.
References org.lightjason.rest.provider.CExecution.parsestringterm().
static void org.lightjason.rest.provider.CExecution.wakeup (final Stream< IAgent<?>> p_agents, final String p_data) static
Parameters
p_agents agent stream
p_data any optional data
Definition at line 104 of file CExecution.java.
References org.lightjason.rest.provider.CExecution.parsestringterm().