LightJason - REST: org.lightjason.rest.CCommon Class Reference
org.lightjason.rest.CCommon Class Reference
class for any helper calls
Classes
class CUTF8Control
class to read UTF-8 encoded property file
Static Public Member Functions
static URL concaturl (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException
concats an URL with a path
static ResourceBundle configuration ()
returns the property data of the package
static ResourceBundle languagebundle ()
returns the language bundle
static String[] languages ()
list of usable languages
static< T > String languagestring (final T p_source, final String p_label, final Object...p_parameter)
returns the language depend string on any object
static String languagestring (final Class<?> p_class, final String p_label, final Object...p_parameter)
returns a string of the resource file
static Logger logger (final Class<?> p_class)
returns a logger instance
static URL resourceurl ()
returns root path of the resource
static URL resourceurl (final String p_file) throws URISyntaxException, MalformedURLException
returns a file from a resource e.g.
static String urlformat (final String p_value)
returns string which is formated for the use within in a URL
Static Public Attributes
static final String PACKAGEROOT = "org.lightjason.rest"
package name
Private Member Functions
CCommon ()
private ctor - avoid instantiation
Static Private Member Functions
static String languagelabel (final Class<?> p_class, final String p_label)
returns the label of a class and string to get access to the resource
static URL resourceurl (final File p_file) throws URISyntaxException, MalformedURLException
returns a file from a resource e.g.
Static Private Attributes
static final ResourceBundle LANGUAGE
language resource bundle
static final Logger LOGGER = CCommon.logger(CCommon.class)
logger
static final ResourceBundle PROPERTIES
properties of the package
Detailed Description
Definition at line 68 of file CCommon.java.
Constructor & Destructor Documentation
org.lightjason.rest.CCommon.CCommon () private
Definition at line 99 of file CCommon.java.
Member Function Documentation
static URL org.lightjason.rest.CCommon.concaturl (final URL p_base, final String p_string) throws MalformedURLException, URISyntaxException static
Parameters
p_base base URL
p_string additional path
Returns
new URL
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 156 of file CCommon.java.
static ResourceBundle org.lightjason.rest.CCommon.configuration () static
Returns
bundle object
Definition at line 139 of file CCommon.java.
References org.lightjason.rest.CCommon.PROPERTIES.
static ResourceBundle org.lightjason.rest.CCommon.languagebundle () static
Returns
bundle
Definition at line 129 of file CCommon.java.
References org.lightjason.rest.CCommon.LANGUAGE.
static String org.lightjason.rest.CCommon.languagelabel (final Class<?> p_class, final String p_label) static private
Parameters
p_class class for static calls
p_label label name of the object
Returns
label name
Definition at line 258 of file CCommon.java.
References org.lightjason.rest.CCommon.PACKAGEROOT.
Referenced by org.lightjason.rest.CCommon.languagestring().
static String [] org.lightjason.rest.CCommon.languages () static
Returns
list of language pattern
Definition at line 119 of file CCommon.java.
static <T> String org.lightjason.rest.CCommon.languagestring (final T p_source, final String p_label, final Object... p_parameter) static
Parameters
p_source any object
p_label label name
p_parameter parameter
Returns
translated string
Template Parameters
T object type
Definition at line 226 of file CCommon.java.
Referenced by org.lightjason.rest.provider.CExecution.belief(), org.lightjason.rest.provider.CAgentProvider.belief(), org.lightjason.rest.provider.CAgentProvider.cycle(), org.lightjason.rest.provider.CAgentGeneratorProvider.generatemultiplebyid(), org.lightjason.rest.provider.CAgentGeneratorProvider.generatesinglebyid(), org.lightjason.rest.provider.CAgentProvider.goal(), org.lightjason.rest.provider.CAgentProvider.goalimmediately(), org.lightjason.rest.provider.CExecution.goaltrigger(), org.lightjason.rest.provider.CAgentProvider.sleep(), org.lightjason.rest.provider.CAgentProvider.view(), and org.lightjason.rest.provider.CAgentProvider.wakeup().
static String org.lightjason.rest.CCommon.languagestring (final Class<?> p_class, final String p_label, final Object... p_parameter) static
Parameters
p_class class for static calls
p_label label name of the object
p_parameter object array with substitutions
Returns
resource string
Definition at line 239 of file CCommon.java.
References org.lightjason.rest.CCommon.languagelabel().
static Logger org.lightjason.rest.CCommon.logger (final Class<?> p_class) static
Parameters
p_class class type
Returns
logger
Definition at line 109 of file CCommon.java.
static URL org.lightjason.rest.CCommon.resourceurl () static
Returns
URL of file or null
Definition at line 166 of file CCommon.java.
Referenced by org.lightjason.rest.CCommon.resourceurl().
static URL org.lightjason.rest.CCommon.resourceurl (final String p_file) throws URISyntaxException, MalformedURLException static
Jar file
Parameters
p_file file
Returns
URL of file or null
Exceptions
URISyntaxException thrown on syntax error
MalformedURLException thrown on malformat
Definition at line 180 of file CCommon.java.
References org.lightjason.rest.CCommon.resourceurl().
static URL org.lightjason.rest.CCommon.resourceurl (final File p_file) throws URISyntaxException, MalformedURLException static private
Jar file
Parameters
p_file file relative to the CMain
Returns
URL of file or null
Exceptions
URISyntaxException is thrown on URI errors
MalformedURLException is thrown on malformat
Definition at line 194 of file CCommon.java.
static String org.lightjason.rest.CCommon.urlformat (final String p_value) static
Parameters
p_value string
Returns
URL formated string
Definition at line 211 of file CCommon.java.
Referenced by org.lightjason.rest.provider.CAgentGroupProvider.unregister().
Member Data Documentation
final ResourceBundle org.lightjason.rest.CCommon.LANGUAGE static private
Initial value:
= ResourceBundle.getBundle(
        MessageFormat.format( "{0}.{1}", PACKAGEROOT, "language" ),
        Locale.getDefault(),
        new CUTF8Control()
    )
Definition at line 81 of file CCommon.java.
Referenced by org.lightjason.rest.CCommon.languagebundle().
final Logger org.lightjason.rest.CCommon.LOGGER = CCommon.logger(CCommon.class) static private
Definition at line 77 of file CCommon.java.
final String org.lightjason.rest.CCommon.PACKAGEROOT = "org.lightjason.rest" static
Definition at line 73 of file CCommon.java.
Referenced by org.lightjason.rest.CApplication.CApplication(), org.lightjason.rest.TestCLanguageLabels.CJavaVistor.label(), and org.lightjason.rest.CCommon.languagelabel().
final ResourceBundle org.lightjason.rest.CCommon.PROPERTIES static private
Initial value:
= ResourceBundle.getBundle(
        MessageFormat.format( "{0}.{1}", PACKAGEROOT, "configuration" ),
        Locale.getDefault(),
        new CUTF8Control()
    )
Definition at line 89 of file CCommon.java.
Referenced by org.lightjason.rest.CCommon.configuration().